#spring:
#  application:
#    name: user-module
#  kafka:
#    bootstrap-servers: localhost:9092
#
#server:
#  port: 8080

spring:
  application:
    name: user-module
  config:
    import: optional:configserver:http://localhost:8888